# Generated by Django 5.2.6 on 2025-11-11 15:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerConnectionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("server_ip", models.GenericIPAddressField()),
                ("server_port", models.IntegerField(default=22)),
                ("server_username", models.CharField(max_length=50)),
                (
                    "server_password",
                    models.TextField(
                        blank=True, help_text="Encrypted password", null=True
                    ),
                ),
                (
                    "server_key",
                    models.TextField(
                        blank=True, help_text="Encrypted key file content", null=True
                    ),
                ),
                (
                    "server_key_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "server_key_type",
                    models.CharField(
                        blank=True,
                        help_text="password or key",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "server_key_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "server_key_content",
                    models.TextField(
                        blank=True, help_text="Encrypted key content", null=True
                    ),
                ),
                (
                    "last_connected",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Last connection timestamp",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Record creation timestamp"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Server Connection History",
                "verbose_name_plural": "Server Connection Histories",
                "db_table": "server_connection_history",
                "ordering": ["-last_connected"],
                "indexes": [
                    models.Index(
                        fields=["user", "-last_connected"],
                        name="server_conn_user_id_d0d0b2_idx",
                    ),
                    models.Index(
                        fields=["-last_connected"],
                        name="server_conn_last_co_ce8749_idx",
                    ),
                ],
            },
        ),
    ]
